### PR TITLE
bump @nestjs/axios from 0.1.0 to 3.0.0

### PR DESCRIPTION
**Pull request by bpedersen2**
Bump axios to 3.0.0

adjust tests to axios 3

supersedes: #568

### CODE REVIEW

**Comment by bpedersen2** [comment]
The last commit fixes:
```
> nest build

src/datasets/dto/update-derived-dataset.dto.ts:16:12 - error TS2612: Property 'pid' will overwrite the base property in 'CreateDerivedDatasetDto'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

16   readonly pid?: string;
              ~~~
src/datasets/dto/update-raw-dataset.dto.ts:16:12 - error TS2612: Property 'pid' will overwrite the base property in 'CreateRawDatasetDto'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

16   readonly pid?: string;
              ~~~
src/origdatablocks/dto/create-origdatablock.dto.ts:66:12 - error TS2612: Property 'ownerGroup' will overwrite the base property in 'OwnableDto'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

66   readonly ownerGroup: string;
```

**Comment by bpedersen2** [comment]
To use `axios 3`, I needed to set the target to `es2022` in tsconfig.json and upgrade the containers to `node-18`.

**Comment by bpedersen2** [comment]
Still need to find out why the unit and api tests now are hanging ( the e2e test runs successful)

**Comment by bpedersen2** [comment]
The tests are passing now.

**Comment by bpedersen2** [comment]
Note that this a breaking change that  requires to use at least node 18.

**Review by nitrosx — APPROVED** [review]

**Comment by nitrosx** [comment]
Waiting for a day, to see if the other reviewers wants to provide additional feedback.

**Comment by nitrosx** [comment]
@bpedersen2 should we close/delete #568?

**Comment by bpedersen2** [comment]
> Waiting for a day, to see if the other reviewers wants to provide additional feedback.

Yes, that would be good (that's why tried to put some of the more active users in, maybe you can add one from PSI as well?)

**Comment by nitrosx** [comment]
@bpedersen2 I'm ready to merge your PR.
Would you be able to solve the conflict on the file package-lock.json?
Thanks

**Comment by bpedersen2** [comment]
> @bpedersen2 I'm ready to merge your PR. Would you be able to solve the conflict on the file package-lock.json? Thanks

Yes, I'll push an update

**Pull request merged**
