### PR TITLE
Upgrade typescript eslint to fix eslint conflicts

### PR DESCRIPTION
**Pull request by minottic**
## Description
See here: https://github.com/typescript-eslint/typescript-eslint/issues/3738

## Motivation
Newer version of eslint, upgrade suggested by dependabot, has conflicts with old version of typescript/eslint, thus the affected packages have been manually updated

## Fixes:

* packages.json
* packages-lock.json

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?

### CODE REVIEW

**Comment by martin-trajanovski** [comment]
Hey @minottic I see you tried to upgrade some dependencies and probably fix some errors in the actions. I have done this already here https://github.com/SciCatProject/scicat-backend-next/pull/178 in one of my PRs. I fixed the unit tests as well and it mainly fixes Raw dataset datablocks API tests. Would be nice if you could look into that and give a feedback.

**Comment by minottic** [comment]
yes, I saw that (after I opened this one actually), but since it was a draft I thought it would be good to have this one ready, since it broke the build. But as I understand now, #178 is ready to be reviewed, correct?

**Comment by martin-trajanovski** [comment]
> yes, I saw that (after I opened this one actually), but since it was a draft I thought it would be good to have this one ready, since it broke the build. But as I understand now, #178 is ready to be reviewed, correct?

Yes #178 is ready to be reviewed.

**Comment by minottic** [comment]
closed by #178

**Pull request closed without merging**
