### PR TITLE
Use package version for OpenAPI

### PR DESCRIPTION
**Pull request by ChuckMoe**
## Description

Uses environment variable set by node for the OpenAPI version number.

## Motivation

Keeps both version numbers in sync

## Changes:

* changed from hard coded string to environment variable

### CODE REVIEW

**Review by bpedersen2 — COMMENTED** [review]
Looks Ok to me

**Review by nitrosx — COMMENTED** [review]
@ChuckMoe just to confirm, you are setting the version of swagger OpenAPI to the version of the OpenAPI swagger npm package version? Is that correct?

Originally this was supposed to be version of the SciCat API.
This PR would change the meaning of it.
If that's the case, I'm not opposed, but I think it should be discussed at the next meeting.

Currently the swagger interface shows the SciCat API version and the OpenAPI version (see image)
image

Is that what you intent to do or you want the npm library version?

**Comment by ChuckMoe** [comment]
@nitrosx This change does not target the OpenAPI version number but the SciCat Version number, aka. the grey box in your picture. It just automatically keeps it in sync.

**Comment by nitrosx** [comment]
Thank you for clarifying.

**Review by nitrosx — APPROVED** [review]

**Pull request merged**
