### PR TITLE
Fetch correct functional accounts file for tests

### PR DESCRIPTION
**Pull request by Ingvord**
Provide test data with test functional accounts in environment agnostic way

### CODE REVIEW

**Comment by Junjiequan** [comment]
I don't understand what is this PR for. Could you explain a little bit why is this change needed?

**Comment by Ingvord** [comment]
@Junjiequan my intention was to load test accounts explicitly in the TestData.js

For that we need to rename `functionalAccount.json.test` to `functionalAccounts.test.json`

Basically that it. However I realized that that file has to be copied around anyway before running the BE. So probably does not make much of a sense...

Is there any config option to specify functional accounts file location for BE?

**Comment by Junjiequan** [comment]
For users runnning the application for the first time they need to `npm run generate:local`, which handles `functionalAccounts.json` file generation and pulls required docker images. 
So, to run the test locally you can choose to `npm run generate:local` or create your own `functionalAccounts.json` in the root directory.

**Comment by Ingvord** [comment]
@Junjiequan Thanks! Good to know!

**Comment by nitrosx** [comment]
@Ingvord we decided to make it harder to use the functional accounts file present in the repo for security reason.
We want site admins or user that deploy scicat to define theirs functional accounts and not use the default ones.
Hopefully this info helps

**Comment by Junjiequan** [comment]
Close this PR as the issue is fixed https://github.com/SciCatProject/scicat-backend-next/issues/1338

**Pull request closed without merging**
