### PR TITLE
feat: new sdk release

### PR DESCRIPTION
**Pull request by nitrosx**
## Description
This PR includes all the changes needed in the BE to upgrade FE to use the new autogenerated SDK

## Motivation
Refactoring in the FE to use the autogenerated SDK requires some changes in the BE also.

## Fixes
* TBD

## Changes:
* TBD

## Tests included
- [x] Included for each change/fix?
- [x] Passing? 

## Documentation
- [x] swagger documentation updated (required for API changes)
- [ ] official documentation updated

### CODE REVIEW

**Comment by martin-trajanovski** [comment]
@nitrosx Just to let you know that I need to test the new sdk with a real data. I will take a dump from the staging database and try to test the functionalities against frontend and backend.

**Comment by nitrosx** [comment]
@martin-trajanovski Fine by me

**Review by nitrosx — COMMENTED** [review]
It looks good to me.
Go ahead and merge

**Review by Junjiequan — APPROVED** [review]
Looks fine to me.

a tip from the nest-js official doc which I've just found few minutes ago
image

**Comment by martin-trajanovski** [comment]
> Looks fine to me.
> 
> a tip from the nest-js official doc which I've just found few minutes ago image

It's a good one @Junjiequan maybe from now on I can try to use it as much as possible. Don't want to refactor all of this in the current PR but it's good to know.

**Comment by martin-trajanovski** [comment]
> Looks fine to me.
> 
> a tip from the nest-js official doc which I've just found few minutes ago image

@Junjiequan I have resolved this in my updated properties and from now on we can think about using it more often.

**Pull request merged**
